language: elixir
elixir:
  - 1.9
otp_release:
  - 23.0
matrix:
  include:
    - elixir: 1.8
      otp_release: 21.3
    - elixir: 1.9
      otp_release: 22.3
    - elixir: 1.10
      otp_release: 22.3
    - elixir: 1.11
      otp_release: 23.0
